# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23132a07eb8ca87ce79fe30f19361a4575c5536202309232f055d093afc0107d2ee933f8b158af142337aca7f724b2f1b5c0df3bf0e9409375c3ce28cf1724b9

test:
  secret_key_base: ae55f2cbd76a6d5fda3543f1b2136c7deda6852a9c652fdc78b5f43fa7f5e9d5a6688326a0971ab0f163425a483313e97a86ec77d1eb4a8f619c911db6c81231

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
